name: esa_biomass_dps
channels:
 - conda-forge
dependencies:
 - python=3.11
 - requests
 - pystac-client
 - rasterio
 - gdal
 - odc-stac
 - odc-geo
 - rioxarray
 - xarray
 - dask
 - numpy
 - pandas
 - pyproj
 - pip: 
   - maap-py
